### ISSUE TITLE
Missing exception when supported JWT library not found

### ISSUE THREAD

**Issue by palminha** [okta/okta-jwt-verifier-php#15]
If we use a supported JWT library (spomky-labs/jose and firebase/php-jwt) but those libraries are not installed with composer the program breaks silently.

It should throw an exception claiming something like "spomky-labs/jose library not found"

**Comment by bretterer** [comment]
This is listed in the readme of the library

```
The library is also designed to use your favorite JWT library. We currently support spomky-labs/jose and firebase/php-jwt You will have to install one of these or create your own adaptor.
```

We purposely do not automatically install one for you via composer because we don't want to make the choice for you.

**Comment by bretterer** [comment]
@heyjones it requires one of the libraries, as the readme states.  there are many different ones that work with it so you need to also include one that you want to use

**Comment by palminha** [comment]
That's the point of my suggestion. If someone forgot to install or missed
installed, it should not be silent. Some kind of exception would be very
helpful

A quinta, 16/08/2018, 15:59, Brian Retterer <notifications@github.com>
escreveu:

**Comment by bretterer** [comment]
I will look at what we can do to improve this

**Comment by palminha** [comment]
Thanks!

A quinta, 16/08/2018, 16:08, Brian Retterer <notifications@github.com>
escreveu:

**Comment by bretterer** [comment]
I am not sure what is seen here, but it seems that it does not silently fail if a library is not installed. If this is still an issue for you, could you please explain steps how to re-produce?

<img width="1368" alt="Screen Shot 2020-08-05 at 11 27 58 AM" src="https://user-images.githubusercontent.com/1906920/89432331-fc433b80-d70e-11ea-9935-605b81914bde.png">
