### ISSUE TITLE
Unable to verify nonce

### ISSUE THREAD

**Issue by devicenull** [okta/okta-jwt-verifier-php#18]
If I use JwtVerifierBuilder::setNonce to provide a notice, I get a warning:

    Undefined index: nonce in vendor/okta/jwt-verifier/src/JwtVerifier.php on line 112

It looks like Okta doesn't actually pass the nonce through when using the code based authentication flow, since 'nonce' doesn't show up in JwtVerifier::getClaims()

**Comment by bretterer** [comment]
Thank you for the report.  I will get this into our flow to take a look at shortly

**Comment by MattCCC** [comment]
Problem still persists in some cases. I believe it's caused when there's no nonce set using setNonce. To get rid of that Notice one could call:
`->setNonce(null)`

hope it helps 👍

**Comment by bretterer** [comment]
You must pass a nonce to the package through `JwtVerifierBuilder` and the `->setNonce` method.  If you don't have a nonce, pass `null` to the method.
