### ISSUE TITLE
Support PS256 ?

### ISSUE THREAD

**Issue by DeepDiver1975** [okta/okta-jwt-verifier-php#24]
It looks like that only RS256 is supported - https://github.com/okta/okta-jwt-verifier-php/blob/1cef6069221c31607806b54b7d36bd610aecaa13/src/Adaptors/SpomkyLabsJose.php#L36

Would it be possible to support other algorithms as well - specifically PS256?

**Comment by bretterer** [comment]
Hello @DeepDiver1975, Currently this library is set up for Okta tokens. We only allow RS256 by design as this is the only key type that we use. There is some re-work of our jwt verifier libraries coming in the future and I can bring this up with the team.

**Comment by bretterer** [comment]
Hi @DeepDiver1975 - As this is an Okta specific library to validate our minted tokens, we are only supporting RS256 at this time.  I appreciate your feedback on this.  If this is causing you any issues with Okta minted tokens, please feel free to create a new issue of what problems you are running into.
