### ISSUE TITLE
Http\Discovery\Exception\PuliUnavailableException: Puli Factory is not available

### ISSUE THREAD

**Issue by 0GiS0** [okta/okta-jwt-verifier-php#25]
Hi! I followed this article https://developer.okta.com/blog/2018/08/23/symfony-react-php-crud-app where he uses this plugin but I have an issue when I include the authentication fragment on my code:

```
    /**
     * @Route("/movies",methods="GET")
     */
    public function index(MovieRepository $movieRepository)
    {
        if (! $this->isAuthorized()) {
            return $this->respondUnauthorized();
        }

        $movies = $movieRepository->transformAll();

        return $this->respond($movies);
    }

```
I get this error when It setups the JWT verifier:

**Exception has occurred.
Http\Discovery\Exception\PuliUnavailableException: Puli Factory is not available**

BTW I'm using Symfony 4...

any ideas?

**Comment by bretterer** [comment]
This is not an error coming from our library here.  It would appear that you do not have everything you need installed through composer.  I would check that all the dependencies you need for your project are indeed included and installed

**Comment by aaronpk** [comment]
It looks like this error is being thrown by the `php-http` discovery library which this library uses. It's not clear to me why Puli is being used though.

**Comment by bretterer** [comment]
Circling back to this, is this still an issue for you?

**Comment by bretterer** [comment]
Closing this as inactive.  If you feel you still have this issue, please check back with us here or open a new issue.

One thing I would suggest, especially with our new version that will be released soon, is that your versions are fully updated in your composer.json file to make sure that all psr-7 standards are met.
