### ISSUE TITLE
Support Carbon version 2

### ISSUE THREAD

**Issue by aaronpk** [okta/okta-jwt-verifier-php#26]
Currently if you install the latest version of Carbon, you are unable to install this library:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for okta/jwt-verifier ^0.2.1 -> satisfiable by okta/jwt-verifier[0.2.1].
    - okta/jwt-verifier 0.2.1 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1] but these conflict with your requirements or minimum-stability.

```

**Comment by mattrmason** [comment]
Second this attempting to install on Laravel 5.8.8 per this blog post [https://developer.okta.com/blog/2019/01/15/crud-app-laravel-vue](url)

> Problem 1
    - Installation request for okta/jwt-verifier ^0.2.1 -> satisfiable by okta/jwt-verifier[0.2.1].
    - Conclusion: remove nesbot/carbon 2.16.1
    - Conclusion: don't install nesbot/carbon 2.16.1
    - okta/jwt-verifier 0.2.1 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2].
    - Can only install one of: nesbot/carbon[1.26.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.26.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.26.2, 2.16.1].
    - Can only install one of: nesbot/carbon[1.26.3, 2.16.1].
    - Can only install one of: nesbot/carbon[1.26.4, 2.16.1].
    - Can only install one of: nesbot/carbon[1.27.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.28.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.29.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.29.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.29.2, 2.16.1].
    - Can only install one of: nesbot/carbon[1.30.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.31.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.31.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.32.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.33.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.34.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.34.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.34.2, 2.16.1].
    - Can only install one of: nesbot/carbon[1.34.3, 2.16.1].
    - Can only install one of: nesbot/carbon[1.34.4, 2.16.1].
    - Can only install one of: nesbot/carbon[1.35.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.35.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.36.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.36.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.36.2, 2.16.1].
    - Can only install one of: nesbot/carbon[1.22.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.22.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.23.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.24.0, 2.16.1].
    - Can only install one of: nesbot/carbon[1.24.1, 2.16.1].
    - Can only install one of: nesbot/carbon[1.24.2, 2.16.1].
    - Can only install one of: nesbot/carbon[1.25.0, 2.16.1].
    - Installation request for nesbot/carbon (locked at 2.16.1) -> satisfiable by nesbot/carbon[2.16.1].

**Comment by JustinLawrenceMS** [comment]
The only fix I've found is to alias the nesbot/carbon version in composer.json.

"nesbot/carbon": "2.17.0 as 1.22"

**Comment by mattrmason** [comment]
Indeed this worked.   I was able to 
`composer require nesbot/carbon:"2.17.0 as 1.22"`
and then install this package without the above errors.

**Comment by Vardkin** [comment]
Same here when attempting to install on Laravel 5.8.15.
Was able to `composer require nesbot/carbon:"2.18.0 as 1.22"` and then `composer require okta/jwt-verifier`

Thank you @JustinLawrenceMS and @mattrmason for the temporary fix.

**Comment by bretterer** [comment]
internal-ref: OKTA-258479
