### ISSUE TITLE
Package spomky-labs/jose is abandoned

### ISSUE THREAD

**Issue by rlbaxter** [okta/okta-jwt-verifier-php#27]
I get the following message when attempting to follow the documentation.

`Package spomky-labs/jose is abandoned, you should avoid using it. Use web-token/jwt-framework instead.`

The examples should probably be updated to recommend the firebase library, web-token library, or some other library that is not abandoned.

**Comment by munir131** [comment]
@bretterer Any plan for this? It is important. 
![image](https://user-images.githubusercontent.com/6319375/57922614-c3c30200-78bd-11e9-8fdd-242b7e4ac5e6.png)

**Comment by Vardkin** [comment]
@munir131 until they address this you can just use:

`composer require firebase/php-jwt`

and set this class as the adapter.

```
$jwtVerifier = (new \Okta\JwtVerifier\JwtVerifierBuilder())  
     ->setAdaptor(new \Okta\JwtVerifier\Adaptors\FirebasePhpJwt())
     ...
```
Unless you want to write a new adapter for the JWT framework and submit a PR :+1:

**Comment by rlbaxter** [comment]
I created a [pull request](https://github.com/okta/okta-jwt-verifier-php/pull/29) to update the documentation to show using the firebase library as the main example. I've never actually contributed on a project like this before, so please let me know if I did something wrong.

**Comment by munir131** [comment]
I think they should merge https://github.com/okta/okta-jwt-verifier-php/pull/22 It is a proper solution using jwt framework. Also fine to use Firebase too. Looks like they are not maintaining this package now, which is disappointed.

**Comment by robertjd** [comment]
Thanks everyone for the feedback. We'll take  a look at this when we can.  Since this is a dev dependency this is lower prio for us.  Though I can certainly empathize with the warnings on dev dependencies, those are annoying 😭

**Comment by bretterer** [comment]
internal-ref: OKTA-258479
