### ISSUE TITLE
$jwtVerifier->metaData is null

### ISSUE THREAD

**Issue by Av1shay** [okta/okta-jwt-verifier-php#31]
Hi
When I try to run the following code:

```
$url = config('app.okta_base_url') . '/oauth2';
$jwtVerifier = (new JwtVerifier\JwtVerifierBuilder())
            ->setAdaptor(new JwtVerifier\Adaptors\FirebasePhpJwt)
            ->setAudience('api://default')
            ->setClientId(config('app.okta_client_id'))
            ->setIssuer($url)
            ->build();
```

`$jwtVerifier->metaData` is null, and I have no idea why.

When I try to run like in the example with `/default`:
`$url = config('app.okta_base_url') . '/oauth2/default';`

metaData is not null, but I get errorCode "E0000015" and errorSummary: "You do not have permission to access the feature you are requesting", I've been told that specifically in my case I don't need to use` /default`, I'm not use it in any of my other API calls.

Any suggestions? 

Thanks in advance!

**Comment by bretterer** [comment]
It sounds like your org may not have a `/default` authorization server.   are you sure you have access to an authorization server  of `/default`?  

You can check at `https://{yourOktaOrg}}-admin.oktapreview.com/admin/oauth2/as`

**Comment by bretterer** [comment]
Closing as stale, If you have any issues still, please feel free to open a new issue
