### ISSUE TITLE
JWT verifier shows Invalid URL.

### ISSUE THREAD

**Issue by elmacho777** [okta/okta-jwt-verifier-php#32]
Hi, I am using the SpomkyLabsJose for the token verification and the connection parameters are exactly the same provided by the client. But it is showing 
**Invalid URL.
200**

We are using OIDC for the SSO. 

Is it an issue with the authorization server? My code is pasted below

```
<?php
$jwt = $_REQUEST['id_token'];

$jwtVerifier = (new \Okta\JwtVerifier\JwtVerifierBuilder())
    ->setDiscovery(new \Okta\JwtVerifier\Discovery\Oauth) // This is not needed if using oauth.  The other option is OIDC
    ->setAdaptor(new \Okta\JwtVerifier\Adaptors\SpomkyLabsJose)
    ->setAudience('api://default')
    ->setClientId('{clientId}')
    ->setIssuer('https://{yourOktaDomain}.com/oauth2/default')
    ->build();

$jwt = $jwtVerifier->verify($jwt);

dump($jwt); //Returns instance of \Okta\JwtVerifier\JWT

dump($jwt->toJson()); // Returns Claims as JSON Object

dump($jwt->getClaims()); // Returns Claims as they come from the JWT Package used

dump($jwt->getIssuedAt()); // returns Carbon instance of issued at time
dump($jwt->getIssuedAt(false)); // returns timestamp of issued at time

dump($jwt->getExpirationTime()); //returns Carbon instance of Expiration Time
dump($jwt->getExpirationTime(false)); //returns timestamp of Expiration Time
```

**Comment by rdkls** [comment]
I just had exactly the same issue. It happens if you're not paying for / using a customer auth server, as only custom auth servers metadata contain jwks_uri.

The problem is in JwtVerifier.php __construct
It retrieves metadata like so:
        $this->metaData = json_decode($request->setUrl($this->issuer.$this->discovery->getWellKnown())->get()->getBody());

And just assumes the response contains jwks_uri. Which it only does for custom auth servers i.e. your base uri is of form `https://${yourOktaDomain}/oauth2/${authServerId}` NOT `https://${yourOktaDomain}/oauth2`

Then, in verify() it attempts to retrieve the (null) jwks_uri and gets that error
Traceback like so:

```
[16-Jul-2020 07:11:58 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: URI must be a string or UriInterface in (php-dir)/vendor/guzzlehttp/psr7/src/functions.php:62
Stack trace:
#0 (php-dir)/vendor/php-http/message/src/UriFactory/GuzzleUriFactory.php(20): GuzzleHttp\Psr7\uri_for(NULL)
#1 (php-dir)/vendor/okta/jwt-verifier/src/Request.php(65): Http\Message\UriFactory\GuzzleUriFactory->createUri(NULL)
#2 (php-dir)/vendor/okta/jwt-verifier/src/Adaptors/FirebasePhpJwt.php(39): Okta\JwtVerifier\Request->setUrl(NULL)
#3 (php-dir)/vendor/okta/jwt-verifier/src/JwtVerifier.php(94): Okta\JwtVerifier\Adaptors\FirebasePhpJwt->getKeys(NULL)
#4 (php-dir)/index.php(447): Okta\JwtVerifier\JwtVerifier->verif in (php-dir)/vendor/guzzlehttp/psr7/src/functions.php on line 62
```

**Comment by bretterer** [comment]
Internal Ref: OKTA-314097

**Comment by bretterer** [comment]
@rdkls I have pushed an update to develop that will throw a Domain exception if there is no jwks_uri in the metadata.

#50

**Comment by abonne01** [comment]
Thanks. 
What is process to update package list?
Still pointing to 1.0 here
https://packagist.org/packages/okta/jwt-verifier

thanks
