### ISSUE TITLE
Installation trouble w/ Carbon

### ISSUE THREAD

**Issue by PenguinTamer** [okta/okta-jwt-verifier-php#35]
Upon running `composer require okta/jwt-verifier` i get this error. Any suggestions?
```
Using version ^0.2.1 for okta/jwt-verifier
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for okta/jwt-verifier ^0.2.1 -> satisfiable by okta/jwt-verifier[0.2.1].
    - Conclusion: remove nesbot/carbon 2.23.1
    - Conclusion: don't install nesbot/carbon 2.23.1
    - okta/jwt-verifier 0.2.1 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.25.1, 1.25.3, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.26.5, 1.26.6, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.37.0, 1.37.1, 1.38.0, 1.38.1, 1.38.2, 1.38.3, 1.38.4, 1.39.0].
    - Can only install one of: nesbot/carbon[1.26.3, 2.23.1].
    - Can only install one of: nesbot/carbon[1.26.4, 2.23.1].
    - Can only install one of: nesbot/carbon[1.26.5, 2.23.1].
    - Can only install one of: nesbot/carbon[1.26.6, 2.23.1].
    - Can only install one of: nesbot/carbon[1.27.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.28.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.29.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.29.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.29.2, 2.23.1].
    - Can only install one of: nesbot/carbon[1.30.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.31.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.31.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.32.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.33.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.34.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.34.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.34.2, 2.23.1].
    - Can only install one of: nesbot/carbon[1.34.3, 2.23.1].
    - Can only install one of: nesbot/carbon[1.34.4, 2.23.1].
    - Can only install one of: nesbot/carbon[1.35.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.35.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.36.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.36.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.36.2, 2.23.1].
    - Can only install one of: nesbot/carbon[1.37.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.37.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.38.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.38.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.38.2, 2.23.1].
    - Can only install one of: nesbot/carbon[1.38.3, 2.23.1].
    - Can only install one of: nesbot/carbon[1.38.4, 2.23.1].
    - Can only install one of: nesbot/carbon[1.39.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.22.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.22.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.23.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.24.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.24.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.24.2, 2.23.1].
    - Can only install one of: nesbot/carbon[1.25.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.25.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.25.3, 2.23.1].
    - Can only install one of: nesbot/carbon[1.26.0, 2.23.1].
    - Can only install one of: nesbot/carbon[1.26.1, 2.23.1].
    - Can only install one of: nesbot/carbon[1.26.2, 2.23.1].
    - Installation request for nesbot/carbon (locked at 2.23.1) -> satisfiable by nesbot/carbon[2.23.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by jakub-klapka** [comment]
For example Laravel switched to Carbon 2 some time ago. Thus using this package with Laravel requires some composer aliasing magic or forking the repo. I can send PR, but it's really just updating carbon version in dependencies... I believe, that Carbon API didn't change that much and I'm using it with Carbon 2 for some time without problems now.

**Comment by PenguinTamer** [comment]
Im using Laravel and developing a RESTful API

**Comment by bretterer** [comment]
A fix you can do until we can get a release of this is to fork this repo, and update carbon to use the newest version.  I believe no changes will be required for this upgrade, even though it is a major version rev.

**Comment by kezek** [comment]
+1.

The Okta PHP SDK also requires nesbot/carbon ^2.0.

**Comment by bretterer** [comment]
Yes, we just updated dependencies in the PHP SDK, but have not done so with current libraries.  

I am not sure when we will be able to address this, but am open to PR's to handle it if you would like to contribute!

**Comment by danielzev** [comment]
FYI, I forked the repo and updated the dependency:

https://github.com/portfolium/okta-jwt-verifier-php

https://github.com/portfolium/okta-jwt-verifier-php/commit/7849581f91b3e5ed29a1318a4c104060f1891997

All tests pass and it seems to work good!

I'll work on submitting a PR later this week to this main repo with the set PR steps.

**Comment by bretterer** [comment]
Internal-ref: OKTA-258479

**Comment by cviebrock** [comment]
@danielzev Any chance you are still planning that PR?

@bretterer Any chance you can update this package so that the dependencies match those in `okta/sdk`?  Seems odd for these two to be out-of-sync for so long.

**Comment by danielzev** [comment]
@cviebrock good callout! I think I just lost track of it. Let me work on that today

**Comment by cwdt** [comment]
> @cviebrock good callout! I think I just lost track of it. Let me work on that today

This would help us out as well, thanks!

**Comment by danielzev** [comment]
This is great! Sorry I have no idea how this slipped my plate. It just got lost in the mix with all of the crazy stuff going on. When can we expect this to be released in a proper tagged version? Thanks all!

**Comment by cwdt** [comment]
@bretterer when do you expect to release a new version? Thanks!

**Comment by bretterer** [comment]
@cwdt I have a PR ready, but have some merge conflicts.   Now, Travis is not playing nice and reporting back (their outage from today still seems to be a problem even though they say its fixed).  Once they get that resolved, i will be able to resolve the conflicts and get a release merged.... for now, you can use the `dev-develop` flag for composer
