### ISSUE TITLE
Nonce does not match

### ISSUE THREAD

**Issue by furqanPSE** [okta/okta-jwt-verifier-php#46]
error message: Nonce does not match what is expected. Make sure to provide the nonce with `setNonce()` from the JwtVerifierBuilder.
please help to fix this issue.

**Comment by MattCCC** [comment]
It depends on auth type you perform, but if you don't need nonce validation you can call ->setNonce(null) which should skip this part

**Comment by bretterer** [comment]
Yes, if you are not using a nonce, I would use the `setNonce(null)` method to skip nonce validation, however I would suggest you have a nonce set up if at all possible.
