### ISSUE TITLE
php-http/httplug outdated dependency prevents composer require

### ISSUE THREAD

**Issue by fidan-mkdir** [okta/okta-jwt-verifier-php#47]
While trying to require `okta/jwt-verifier`, we get the following error:

`
Problem 1
    - Installation request for okta/jwt-verifier ^0.4.0 -> satisfiable by okta/jwt-verifier[0.4.0].
    - okta/jwt-verifier 0.4.0 requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0] but these conflict with your requirements or minimum-stability.
`

We are using php-http/httplug:^2.1.0 because of other dependencies.

**Comment by makedirectory** [comment]
This commit fixes the issue by adding updated dependencies

https://github.com/makedirectory/okta-jwt-verifier-php/commit/636970bcaa30be9fa2a13289549effdad7e5bc62

**Comment by bretterer** [comment]
We are in the process of updating this library and have updated all dependencies in PR #49.

This will be available in `dev-develop` or in v1 when we release it.

I am going to close this as resolved for now.  If you need further help, please reach back out or open a new issue.
