### ISSUE TITLE
No usage doc explanation

### ISSUE THREAD

**Issue by rdegges** [okta/okta-jwt-verifier-php#55]
The usage docs for this library are pretty blank. It currently just shows a code snippet with no explanation of what's going on. It'd be cool to get a read guide that explains what JWTs are, what this library does in more detail, and how to work with JWTs using this library.

**Comment by bretterer** [comment]
@rdegges Does this resolve the issue here?   https://github.com/okta/okta-jwt-verifier-php/tree/update_readme

**Comment by rdegges** [comment]
Great!!
