### ISSUE TITLE
Nonce does not match what is expected

### ISSUE THREAD

**Issue by adam-ut** [okta/okta-jwt-verifier-php#63]
Hi,

This client is great. Thanks for building it. The only part tripping me up is the nonce.

I'm using Okta ODIC. We're doing client side verification in a react app and I plan on passing the id_token to our API for validation and pass back a session token.

```php
$jwtVerifier = (new \Okta\JwtVerifier\JwtVerifierBuilder())
  ->setDiscovery(new \Okta\JwtVerifier\Discovery\Oidc)
  ->setAdaptor(new \Okta\JwtVerifier\Adaptors\FirebasePhpJwt)
  ->setAudience('{client_id}')
  ->setClientId('{client_id}')
  ->setIssuer('https://{custom}.okta.com')
  ->setNonce(null)
  ->build();

$jwt = $jwtVerifier->verify($okta_jwt);
```

This results in:
`Nonce does not match what is expected. Make sure to provide the nonce with 'setNonce()' from the JwtVerifierBuilder.`

The id_token already has a nonce and the verifier is trying to check that the nonce for the builder matches. If I don't include setNonce or pass in null to setNonce, I still get the same error. I'm I doing something wrong here? If I set the nonce manually to what I know it is in the token, everything appears to work fine.

My only other thought to get around this is to build my own Adaptor where after the decode I set the nonce to null. I may need to do this anyway since my Okta setup doesn't return a cid in the jwt; the client id comes back as in the aud field.

Any thoughts you have on this would be greatly appreciated.

**Comment by bretterer** [comment]
Hi @adam-ut, I am happy to hear you are getting use out of this package and liking it.

We do require you to pass a nonce in to make sure the token is valid and not spoofed. This is a security feature for you. Unless I am misunderstanding what is expected here, you are trying to bypass the nonce check, which is not currently available.

Is this something that is common in your use case that you don't need to verify the nonce is correct? Can you expand on how your current flow works a little more to help me understand this?

**Comment by adam-ut** [comment]
Thanks for the response, @bretterer. 

The workflow is:
1. React app starts up
2. React app validates user is logged in. If not, all authorization occurs at the client/js level.
3. React app sends request to API with current session id (not Okta JWT). If the session id doesn't exist, or is expired, it passes the Okta JWT to the API.
4. API looks for session id. If it doesn't exist, or it is expired, it looks at the Okta JWT and verifies the contents. A new session id is generated and passed back from the API along with the request.

From what I see in the code, the only calls out to our company's Okta endpoint are to get the well-known data as well as the keys associated with Okta for verification. The PHP script was not part of generating the Okta JWT, so it doesn't have a nonce to compare with to validate that the nonce in the JWT is the same. However, since the Okta JWT has been verified with the key, and has not expired, the contents are taken as verified.

Does that clarify my question? I'd be happy to provide more details if you're interested. Because of my other issue with cid not being passed back, I was able to get around both issues through a custom Adaptor based on the FirebasePhpJwt Adaptor in your library. Also, I'll completely understand if this is a "working as designed" situation.

Thanks again!

**Comment by bretterer** [comment]
I believe this is working as design, but am interested in your adaptor that you created. If you wanted to submit a PR with it against this repo, I would be more than happy to take a look and possibly merge it in if it fits a use case that we don't cover, which it sounds like it may.

Let me know if this is something you would be interested in doing. if you do, please submit a CLA if you havent already. developer.okta.com/cla

**Comment by adam-ut** [comment]
I don't think my code warrants a PR as it feels like my solution is very niche. However, if anyone else is interested, I'll add the answer here.

```php
class CustomFirebasePhpJwt extends FirebasePhpJwt {
  public function decode($jwt, $keys): Jwt {
    FirebaseJWT::$leeway = 120;
    $decoded = (array)FirebaseJWT::decode($jwt, $keys, ['RS256']);
    unset($decoded['nonce']);
    if(isset($decoded['aud'])) {
      $decoded['cid'] = $decoded['aud'];
    }

    return (new Jwt($jwt, $decoded));
  }
}
```

So, I extended the adapter and overrode the decode function.

Thank you again for your direction, @bretterer!

**Comment by kblizeck** [comment]
@adam-ut I am having the same issues, and am trying to replicate your custom adaptor above. This is just used to replace the `setAdaptor` in the `jwtVerifier` call, correct?

```
$jwtVerifier = (new JwtVerifierBuilder())
	->setAdaptor(new CustomFirebasePhpJwt)
	->setAudience(OKTA_CLIENTID)
	->setClientId(OKTA_CLIENTID)
	->setNonce(null)
        ->setIssuer('https://' . OKTA_HOST . '/oauth2/default')
	->build();
```
