### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by pmxjason** [okta/okta-jwt-verifier-php#66]
Hello,

Is adding PHP8 support to this library on the roadmap? Lack of support is going to become a blocker on a number of our projects. 

Any indication of when this can be expected would be much appreciated.

**Comment by laura-rodriguez** [comment]
Hi @pmxjason,

Thank you for your question. I'll ask internally and give you an update when I have more details.

**Comment by bretterer** [comment]
Hi @pmxjason, We have not currently done any compatibility work on adding PHP8 support for this repository. From a very high level review, it seems that there are only some packages that will need to be updated in order to allow for PHP8 to be used. Have you done any testing yourself to see if this will work out of the box? What findings have you found that are a blocker for your team so we can make sure to address them?

**Comment by pmxjason** [comment]
@bretterer I agree that it doesn't look like there is much work to make a PHP8 compatible version. My team hasn't spent any time attempting to update the package. We would still be blocked without an official version as our internal security review forbids homebrew/modified security and authentication libraries.

I might misunderstand. I thought our business was sold Okta in part due to the ease of integration into .net / php applications. I will feed it back up the chain to see if I have permission to invest time in this.

**Comment by bretterer** [comment]
@pmxjason I'm sorry if it came across as us not doing the work. I was honestly just curious if you had done any on your end to help unblock you.

Please watch this ticket for updates soon on steps we will be taking to update this package as well as our management sdk for PHP8 support. 

- Brian

**Comment by pmxjason** [comment]
I may have misinterpreted your response. I got blocked on something else and had a quick attempt to get something running. 

I forked the code base and made the following single change to the composer.json file.

```
"php": "^7.2|^8.0",
```

I then pulled in my forked repo and ran:

```
$jwtVerifier = (new \Okta\JwtVerifier\JwtVerifierBuilder())
    ->setAdaptor(new \Okta\JwtVerifier\Adaptors\FirebasePhpJwt())
    ->setAudience('api://default')
    ->setClientId('0oaerwa0pccy7Kb4N416')
    ->setIssuer('https://iris.okta.com/oauth2/default')
    ->build();
try {
    $jwt = $jwtVerifier->verify($token);
} catch (\Exception $e) {
    var_dump($e);
}
```

This ran fine without error. Valid tokens worked, invalid tokens through an exception. I haven't run the tests.

**Comment by bretterer** [comment]
@pmxjason Thank you for the information here. I will talk with our team to figure out when we can get this on our schedule to update.

**Comment by duylaurent-tran** [comment]
Do you have any news when it will be compatible with version 8 of PHP?

**Comment by lerayflorian** [comment]
Hi,
Given the delay, I'd say Okta isn't able to cope with pace of modern softwares. It still asks me to be on php 7.2...  (while 7.3 dates back to December 2018!!!). I'll thus probably be forced to drop Okta. May this post be some good piece of advice for people assessing Okta's relevance to their needs.
Florian

**Comment by ctrl-f5** [comment]
Can this be prioritized please? PHP8.1 is around the corner, 7.2 which is the min version currently in the package is already end of life.

And it seems like the code is basically compatible with 8, it just needs to be tested on that version and composer versions need to be aligned...

**Comment by ctrl-f5** [comment]
I have created an MR to add 8.0 and drop 7.2. I suggest tagging this as 2.0 and if people still want to use 7.2 they can still use the 1.x branch.

**Comment by vkhramtsov** [comment]
Any news here?

**Comment by vkhramtsov** [comment]
@laura-rodriguez @bretterer php 8.0 was out 8 months ago, php 7.3 will reach EOL in 3 mohths, php 7.4 will be moved to security fixes only state in 3 moths. Do we have any chance to get version of package compatible with php 8.0? Currently this is only  package that prevent us from upgrade to php 8.0. Should we wait for update or it is beter to look for to another jwt verifier package?
Thank you in advance.

**Comment by vkhramtsov** [comment]
@bretterer thank you for merging php 8 support to develop. Would you be so kind to create new release?
Thank you in advance.

**Comment by vkhramtsov** [comment]
@bretterer Thank you for creating release.
@pmxjason looks like you can close this ticket.
