### ISSUE TITLE
ClassInstantiationFailedException: Unexpected exception when instantiating class

### ISSUE THREAD

**Issue by goalkeeper007** [okta/okta-jwt-verifier-php#69]
I am new to this module. I followed the installation instructions, installed firebase and psr7 dependencies along with the okta/okta-jwt-verifier-php module. I am getting this error, I went through open issues and could not find one. Please let me know how I can fix this or if a workaround exists. Really appreciate any help.

{"xdebug_message":"<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )<\/span> 
Http\\Discovery\\Exception\\ClassInstantiationFailedException: Unexpected exception when instantiating class. in \/root\/code\/app\/vendor\/php-http\/discovery\/src\/ClassDiscovery.php on line <i>220<\/i>
<\/th><\/tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack<\/th><\/tr>\n<tr><th align='center' bgcolor='#eeeeec'>#<\/th><th align='left' bgcolor='#eeeeec'>Time<\/th><th align='left' bgcolor='#eeeeec'>Memory<\/th><th align='left' bgcolor='#eeeeec'>Function<\/th><th align='left' bgcolor='#eeeeec'>Location<\/th><\/tr>\n<tr><td bgcolor='#eeeeec' align='center'>1<\/td><td bgcolor='#eeeeec' align='center'>3.1931<\/td><td bgcolor='#eeeeec' align='right'>362968<\/td><td bgcolor='#eeeeec'>{main}(  )<\/td><td title='\/root\/code\/app\/restapi\/v1\/index.php' bgcolor='#eeeeec'>...\/index.php<b>:<\/b>0<\/td><\/tr>\n<tr>

PHP 7.4.8

**Comment by bretterer** [comment]
Hi @goalkeeper007.  From your error provided, it is a little hard to determine what is happening.

Can you expand your ticket here with some code samples that you have, with your issuer, as well as a full stacktrace?

**Comment by goalkeeper007** [comment]
Here is the code where it was failing
$jwtVerifier = (new \Okta\JwtVerifier\JwtVerifierBuilder())
            ->setAdaptor(new \Okta\JwtVerifier\Adaptors\FirebasePhpJwt)
            ->setIssuer($ISSUER)
            ->setAudience('api://default')
            ->setClientId($OAUTH2_CLIENT_ID)
            ->build();

where
$ISSUER = "https://dev-85466444.okta.com/oauth2/default"
$OAUTH2_CLIENT_ID = <my client id from dev-85466444.okta.com>

stacktrace-
$e->getTraceAsString()
"#0 /root/code/app/vendor/php-http/discovery/src/HttpClientDiscovery.php(30): Http\Discovery\ClassDiscovery::instantiateClass()
#1 /root/code/app/vendor/okta/jwt-verifier/src/Request.php(56): Http\Discovery\HttpClientDiscovery::find()
#2 /root/code/app/vendor/okta/jwt-verifier/src/Adaptors/FirebasePhpJwt.php(41): Okta\JwtVerifier\Request->__construct()
#3 /root/code/app/restapi/v1/ping.php(85): Okta\JwtVerifier\Adaptors\FirebasePhpJwt->__construct()
#4 /root/code/app/restapi/v1/ping.php(68): verifyJwt()
#5 [internal function]: {closure}()
#6 /root/code/app/vendor/slim/slim/Slim/Route.php(468): call_user_func_array()
#7 /root/code/app/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#8 /root/code/app/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /root/code/app/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /root/code/app/src/middleware/SetHeaders.php(34): Slim\Midd"

*Exception*previous trace:
Http\Discovery\Exception\DiscoveryFailedException
Exception*previous:Http\Discovery\Exception\NotFoundException
message:"No PSR-17 response factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation"
*Exception*string:""
code:0
file:"/root/code/app/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php"
line:22

Looking at the previous exception trace, i installed http-interop/http-factory-guzzle (although guzzlehttp/psr7 was installed and that should have been enough). This fixed the issue for me. I am documenting this so that others can find it.

Thank you @bretterer appreciate your help.

**Comment by bretterer** [comment]
Thank you @goalkeeper007 It sounds like guzzlehttp/psr7 still hasn't released their new version.  Their Psr17FactoryDiscovery is still only in a branch.  ref: https://github.com/okta/okta-jwt-verifier-php/issues/59#issuecomment-707749309
