### ISSUE TITLE
JwtVerifierBuilder : checks

### ISSUE THREAD

**Issue by abonne01** [okta/okta-jwt-verifier-php#74]
Hello,

I saw some hardcoded string in JwtVerifierBuilder.php file.
When authentification object is checked, it's comparing with a "dummy" entry : 

```php
        if (strstr($issuer, "{yourOktaDomain}") != false) {

        if (strstr($cid, "{clientId}") != false) {
```

is it something wanted? this check in totally irrelevant.
Thanks

**Comment by bryanapellanes-okta** [comment]
@abonne01,
Thanks for reaching out! These appear to be our standard checks to ensure that your configuration does not contain default place holders.  I will follow up with our Php developers so they may add any additional relevant details.

Thanks for using Okta!

Thanks for using Okta!

**Comment by bretterer** [comment]
Hi @abonne01,

These checks are correct as they are. We have them to help prevent `copy/paste` errors from documentation. In our documentation, we use these placeholders for things like issuer: `https://{yourOktaDomain}/oauth2/v1/default`. These checks are here to help you understand what may be happening.

A little background:

We've seen in user testing that it is too easy to

- Copy and paste the browser URL that includes -admin
- Copy the right URL, but mis-paste it (such as pasting it twice)
- Forget to replace the {yourOktaDomain} placeholder altogether
