### ISSUE TITLE
validateClaims() called without type from verify()

### ISSUE THREAD

**Issue by lex0r** [okta/okta-jwt-verifier-php#75]
Hi, after reviewing the latest master I came to a conclusion that this call is not a valid one (the 2nd argument is missing):

https://github.com/okta/okta-jwt-verifier-php/blob/22a1c0aa9db68917c513cd6883bf3d74d5e5e3a4/src/JwtVerifier.php#L106

Is `verify()` now irrelevant?

**Comment by bryanapellanes-okta** [comment]
@lex0r,
Thanks for reaching out!  I'll bring your question to the attention of our Php developers to get you an answer.  

Thanks for using Okta!

**Comment by bretterer** [comment]
@lex0r, you are absolutely correct.  I will push a fix in a few minutes.  

You are correct though, I would suggest using verifyIdToken and verifyAccessToken instead of `verify()`

**Comment by bretterer** [comment]
Thank you again for bringing this to our attention.  `verify` now works as it did before, and validates as an `accessToken`. Sorry for the introduced bug, we will look at how we can make sure this doesn't happen in the future.

You can download the newest version 1.1.1 from packagist
