### ISSUE TITLE
Are there any plans for PHP 8.1 support in the near future?

### ISSUE THREAD

**Issue by jelrikvh** [okta/okta-jwt-verifier-php#89]
Hello,

When PHP 8.0 came out, we had to wait a long time for the simple `composer.json` update in this package. PHP 8.1 has been out for more than a month. What is the planning for the update to 8.1?

Would it be a possibility to add `^8.0` to the `composer.json`, so we don't have this problem with 8.2, 8.3, and 8.4 later on?

Thanks a lot,
Jelrik van Hal

**Comment by bretterer** [comment]
@jelrikvh,

Thank you for the question about 8.1 update. I have brought this issue to our product team to investigate the upgrade and to find a place for it in our workload. Although this appears to be a pretty straight forward update in the composer file, we have a lot of things to make sure they still work in prior versions of PHP as well.  Please bear with us as we discuss this internally.

**Comment by jelrikvh** [comment]
I understand there's more to test, but PHP 8.1 has been out for more than a month as a stable release and at least half a year before as beta and release candidates. I'm shocked that I have to be the one to put this on your backlog, as we pay money for the use of Okta, which is now impairing our ability to use the most secure, fast, and up-to-date tools available.

I would say: run your tests and you know whether it works.

**Comment by bretterer** [comment]
@jelrikvh We have released version 1.3.0 which includes updates to support PHP 8.1

Please let us know if you run into any issues.
