### ISSUE TITLE
Understanding JwT verification - Expiration Time and Signature

### ISSUE THREAD

**Issue by agawronski** [okta/okta-jwt-verifier-php#92]
Thank you for your work on the okta-jwt-verifier-php.

I am trying to make sure that I am using this correctly:
[https://github.com/okta/okta-jwt-verifier-php#validating-an-access-token](https://urldefense.com/v3/__https:/github.com/okta/okta-jwt-verifier-php*validating-an-access-token__;Iw!!LUQEDAk!v4kg93ba6oUlpJRsW-UIq936VNT2BU2F8UVuOmM7jSrltqQ6JTZBZjr8F81l-egaD_keNvvJaSJl5dAuA0Ab0mJFbQ$)

`$jwt = $jwtVerifier->verifyAccessToken($jwtString);`
**•	token expiration time**
•	the time it was issue at
•	that the token issuer matches the expected value passed into the above helper
•	that the token audience matches the expected value passed into the above helper

I don't see anywhere in the code that actually checks the token expiration time. Am I missing something?

I am also trying to understand where the signature verification occurs.

Thanks,
Aidan.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting @agawronski !

@bretterer can you please take a look?

**Comment by agawronski** [comment]
Any luck with this? 

Does verifyAccessToken actually secure the app? or just decode the token?
